package com.gestion.App.Demande;

import jakarta.persistence.Entity;

import jakarta.persistence.*;
import lombok.Data;

import java.sql.Timestamp;
import java.util.Date;

@Entity
@Data
@Table(name = "Demandes")
public class Demande {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID_Demande")
	private Long idDemande;

	@Column(name = "Type_Demande",nullable = false)
	private String typeDemande;

	@Column(name = "Description", columnDefinition = "TEXT")
	private String description;

	@Column(name = "rub_id")
	private Long code;

	@Column(name = "Date_Soumission",nullable = false,insertable = false, updatable = false)
	private Timestamp dateSoumission;

	@Column(name = "ID_User")
	private Long idUser;

	@Column(name = "Statut", length = 50, columnDefinition = "VARCHAR(50) DEFAULT 'En Attente'")
	private String statut;

	// Getters and Setters

	// You don't need a setIdDemande method when using @GeneratedValue
	// The ID will be automatically generated by the database
}
